### PR TITLE
feat: add v18.20.2 patch

### LINKED ISSUE #31: Node 18.20.1 security release
Node.js [just announced the release of 18.20.1](https://nodejs.org/en/blog/release/v18.20.1) security release. 

This fork seems to be the most active from the original pkg, and has been keeping up with releases. It'll be great if we could get support for 18.20.1 for all main platforms. 

Thank you!

### PR DESCRIPTION
**Pull request by keegan-w**
Fixes #31 

I've created patch for 18.20.2.

Please review when you get a chance. Thanks in advance

### CODE REVIEW

**Comment by robertsLando** [comment]
@keegan-w I have reverted nodejs 20 patches as seems the one I created is broken. If you want to take a look at that too let me know so I can wait before doing new release 🙏🏼

**Comment by robertsLando** [comment]
Fixes #31

**Comment by keegan-w** [comment]
I ran that test on windows and it completed successfully :) , i've also been testing the built binary inside my web server application and it has continued to work as previously. 

Not sure how much time I'll get to look at the Node 20 issues though....  Seemed like there a few people wanting this version with the latest node js security updates (myself included 😄), so it may helpful to publish a release in the interim.

**Comment by robertsLando** [comment]
@keegan-w Builds fail: https://github.com/yao-pkg/pkg-fetch/actions/runs/9282337155/job/25590915317

**Comment by robertsLando** [comment]
@keegan-w news about this?

**Comment by robertsLando** [comment]
The issue is:

```
#17 146.5 ../deps/cares/src/lib/ares_rand.c:39:12: fatal error: sys/random.h: No such file or directory
#17 146.5    39 | #  include <sys/random.h>
#17 146.5       |            ^~~~~~~~~~~~~~
#17 146.5 compilation terminated.
#17 146.5 make[1]: *** [deps/cares/cares.target.mk:199: /tmp/pkg.5b572aede55a6d701bf2fd33/node/out/Release/obj.target/cares/deps/cares/src/lib/ares_rand.o] Error 1
#17 146.5 make[1]: *** Waiting for unfinished jobs....
#17 146.6 make: *** [Makefile:134: node] Error 2
```

By doing some research seems this is a known issue related to the glibc version https://github.com/nodejs/node/issues/52223

The suggested fix is to patch a nodejs file like explained here: https://github.com/tsibley/conda-forge-nodejs-feedstock/commit/5eb5c33d4259e36e878081ba6a92dcbc0e984c53


https://github.com/tsibley/conda-forge-nodejs-feedstock/commit/5eb5c33d4259e36e878081ba6a92dcbc0e984c53

**Pull request merged**
