### PR TITLE
feat: support for latest NodeJS v20

### PR DESCRIPTION
**Pull request by glektarssza**
Seems to be working!

image

### CODE REVIEW

**Comment by robertsLando** [comment]
Crossed fingers 🤞🏼 https://github.com/yao-pkg/pkg-fetch/actions/runs/7083731774

**Comment by robertsLando** [comment]
@ptaferner Are you using pkg master branch? Dunno if it could be someway related to https://github.com/yao-pkg/pkg/pull/8

**Comment by robertsLando** [comment]
I may have a fix for arm64 too: https://github.com/yao-pkg/pkg-fetch/actions/runs/7087579394/job/19288161530

**Comment by ptaferner** [comment]
> @ptaferner Are you using pkg master branch? Dunno if it could be someway related to [yao-pkg/pkg#8](https://github.com/yao-pkg/pkg/pull/8)

Ah, many thanks! This has indeed resolved the problem and my app runs now! :)

**Comment by robertsLando** [comment]
@ptaferner Did you reverted that change and it worked so? Strange...

**Pull request merged**
